## Numpy Revision by Raafid Shahab

# 1. Five methods of Array Creation

In [1]:
import numpy as np

### 1.1) np.array()

In [2]:
#1-D Array
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
#2-D Array
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
#3-D Array
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### 1.2) np.zeros(), np.ones(), np.identity()

In [5]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr4 = np.ones((3,2,2))
arr4

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [7]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 1.3) np.arange()

In [8]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1.4) np.linspace()

In [9]:
arr7 = np.linspace(10,30,5)
arr7

array([10., 15., 20., 25., 30.])

### 1.5) arr.copy()

In [10]:
arr8 = arr7.copy()
arr8

array([10., 15., 20., 25., 30.])

# 2. Six Attributes

### arr.shape, arr.ndim, arr.size, arr.itemsize, arr.dtype, arr.astype()*

In [11]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr4

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [13]:
arr2.shape
#gives shape, no of rows and columns

(2, 3)

In [14]:
arr4.shape

(3, 2, 2)

In [15]:
arr2.ndim
#gives the dimension of array

2

In [16]:
arr4.ndim

3

In [17]:
arr2.size
#gives no pf elements in an array

6

In [18]:
arr2.itemsize #int= 4
#gives size of each element of an array

4

In [19]:
arr4.itemsize
#float= 8

8

In [20]:
arr2.dtype

dtype('int32')

In [21]:
arr4.dtype

dtype('float64')

In [22]:
arr2.astype('float')
#this is function, converts data type

array([[1., 2., 3.],
       [4., 5., 6.]])

# 3. Numpy Array vs Pyhton Lists

- Faster
- Convinient
- Less Memory

In [23]:
#Proof of Faster & Convinient

#Python List
import time as t
x = range(100000)
y= range(1000000,2000000)
start_time = t.time()
c = [(x,y) for x,y in zip(x,y)]
print(t.time() - start_time)

0.03002309799194336


In [24]:
#Numpy Array
a= np.arange(100000)
b= np.arange(100000,200000)
start_time = t.time()
c = a+ b #proof of convinient Mathematical Operations
print(t.time() - start_time)

0.004000186920166016


# 4. Indexing, slicing and iteration

In [25]:
arr1

array([1, 2, 3, 4, 5])

In [26]:
arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
arr1[3]
#gives the element at index 3

4

In [28]:
arr1[-1]
#gives the last element

5

In [29]:
arr12[3]
# for 2D array, the first index identifies row

array([12, 13, 14, 15])

In [30]:
arr12[:,2]
#all rows, 3rd column

array([ 2,  6, 10, 14, 18, 22])

In [31]:
arr12[2:4,1:4]
#slicing

array([[ 9, 10, 11],
       [13, 14, 15]])

In [32]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [33]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


# 5. Numpy Operations

In [34]:
arr1

array([1, 2, 3, 4, 5])

In [35]:
arr2 = np.array([4,5,6,7,8])
arr2

array([4, 5, 6, 7, 8])

In [36]:
# Addition
arr1 + arr2

array([ 5,  7,  9, 11, 13])

In [37]:
# Subtrcaction
arr1 - arr2

array([-3, -3, -3, -3, -3])

In [38]:
# Scalar Multiplication
arr1*2

array([ 2,  4,  6,  8, 10])

In [39]:
# Vector Multiplication
arr1*arr2

array([ 4, 10, 18, 28, 40])

In [40]:
#Boolean Series output
arr1>3

array([False, False, False,  True,  True])

In [41]:
arr3 = np.arange(6).reshape(2,3)
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
arr4 = np.arange(6,12).reshape(3,2)
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [43]:
#Dot Product
arr3.dot(arr4)
# *condition: no. of columns of first array should be equal to no of rows of second array

array([[ 28,  31],
       [100, 112]])

In [44]:
arr4.max()

11

In [45]:
arr4.min()

6

In [46]:
arr4.min(axis=0)
# column wise minimum

array([6, 7])

In [47]:
arr4.min(axis=1)
# Row wise minimum

array([ 6,  8, 10])

In [48]:
arr4.sum()
#sum of all elements

51

In [49]:
arr4.mean()

8.5

In [50]:
arr4.std()

1.707825127659933

In [51]:
np.median(arr4)

8.5

In [52]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

# 6. Reshaping Numpy Arrays

In [53]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

### Reshape method

In [54]:
arr4.reshape(2,3)

array([[ 6,  7,  8],
       [ 9, 10, 11]])

### Ravel method

In [55]:
arr4.ravel()
#converts in 1D Array for any n-dimensional araay

array([ 6,  7,  8,  9, 10, 11])

### Transpose method

In [56]:
arr4.transpose()
#rows and columns get interchanged

array([[ 6,  8, 10],
       [ 7,  9, 11]])

### Stacking

In [57]:
arr5 = np.arange(12,18).reshape(2,3)
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [58]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
#Horizontal Stack
np.hstack((arr3,arr5))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [60]:
#Vertical Stack
np.vstack((arr3,arr5))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

### Splitting

In [61]:
#Vertical Splitting
np.vsplit(arr3,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [62]:
#Horizontal Splitting
np.hsplit(arr5,3)

[array([[12],
        [15]]),
 array([[13],
        [16]]),
 array([[14],
        [17]])]