## Numpy Revision by Raafid Shahab

# 1. Five methods of Array Creation

In [1]:
import numpy as np

### 1.1) np.array()

In [2]:
#1-D Array
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
#2-D Array
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
#3-D Array
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### 1.2) np.zeros(), np.ones(), np.identity()

In [5]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr4 = np.ones((3,2,2))
arr4

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [7]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 1.3) np.arange()

In [8]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1.4) np.linspace()

In [9]:
arr7 = np.linspace(10,30,5)
arr7

array([10., 15., 20., 25., 30.])

### 1.5) arr.copy()

In [10]:
arr8 = arr7.copy()
arr8

array([10., 15., 20., 25., 30.])

# 2. Six Attributes

### arr.shape, arr.ndim, arr.size, arr.itemsize, arr.dtype, arr.astype()*

In [37]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr4

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [20]:
arr2.shape
#gives shape, no of rows and columns

(2, 3)

In [42]:
arr4.shape

(3, 2, 2)

In [32]:
arr2.ndim
#gives the dimension of array

2

In [43]:
arr4.ndim

3

In [33]:
arr2.size
#gives no pf elements in an array

6

In [34]:
arr2.itemsize #int= 4
#gives size of each element of an array

4

In [40]:
arr4.itemsize
#float= 8

8

In [35]:
arr2.dtype

dtype('int32')

In [41]:
arr4.dtype

dtype('float64')

In [44]:
arr2.astype('float')
#this is function, converts data type

array([[1., 2., 3.],
       [4., 5., 6.]])

# 3. Numpy Array vs Pyhton Lists

- Faster
- Convinient
- Less Memory

In [50]:
#Proof of Faster & Convinient

#Python List
import time as t
x = range(100000)
y= range(1000000,2000000)
start_time = t.time()
c = [(x,y) for x,y in zip(x,y)]
print(t.time() - start_time)

0.042478322982788086


In [51]:
#Numpy Array
a= np.arange(100000)
b= np.arange(100000,200000)
start_time = t.time()
c = a+ b #proof of convinient Mathematical Operations
print(t.time() - start_time)

0.0071027278900146484


# 4. Indexing, slicing and iteration

In [63]:
arr1

array([1, 2, 3, 4, 5])

In [56]:
arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [58]:
arr1[3]

4

In [62]:
arr1[-1]

array([20, 21, 22, 23])

In [64]:
arr12[3]

array([12, 13, 14, 15])

In [66]:
arr12[:,2]
#all rows, 3rd column

array([ 2,  6, 10, 14, 18, 22])

In [67]:
arr12[2:4,1:4]

array([[ 9, 10, 11],
       [13, 14, 15]])

In [68]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [70]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


# 5. Numpy Operations